name: astral_game
description: "Astral Game Client"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0
  

dependencies:
  flutter:
    sdk: flutter
  astral_rust_core:
    path: ../../packages/astral_rust_core
  vpn_service_plugin:
    path: ../../packages/vpn_service_plugin
  basic_utils: ^5.6.1
  pointycastle: ^3.9.1
  window_manager: ^0.4.3
  flex_color_scheme: ^8.4.0
  get_it: ^9.2.0
  signals: ^6.3.0
  signals_flutter: ^6.3.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.3
  path_provider: ^2.1.4
  webdav_client: ^1.2.2
  archive: ^4.0.2
  path: ^1.9.0
  package_info_plus: ^8.3.0
  image_picker: ^1.1.1
  http: ^1.2.2
  event_bus: ^2.0.0
  logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
