// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_instance_info`, `handle_event_with_instance_id`, `lookup_app_rpc`, `parse_instance_id`, `peer_conn_info_to_string`, `send_udp_to_localhost_with_instance_id`, `tracing_log_lagged`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MANAGER`, `RT`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `deref`, `deref`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `initialize`, `initialize`

Future<void> sendUdpToLocalhost({required String message}) =>
    RustLib.instance.api.crateApiP2PSendUdpToLocalhost(message: message);

Future<JoinHandle> handleEvent({required EventBusSubscriber events}) =>
    RustLib.instance.api.crateApiP2PHandleEvent(events: events);

Future<String> easytierVersion() =>
    RustLib.instance.api.crateApiP2PEasytierVersion();

Future<bool> isEasytierRunning({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PIsEasytierRunning(instanceId: instanceId);

Future<List<String>> getIps({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PGetIps(instanceId: instanceId);

Future<void> setTunFd({required String instanceId, required int fd}) =>
    RustLib.instance.api.crateApiP2PSetTunFd(instanceId: instanceId, fd: fd);

Future<String> getRunningInfo({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PGetRunningInfo(instanceId: instanceId);

Future<JoinHandleResultStringString> createServer({
  required String configToml,
  required bool watchEvent,
}) => RustLib.instance.api.crateApiP2PCreateServer(
  configToml: configToml,
  watchEvent: watchEvent,
);

Future<String> joinHandleResult({
  required JoinHandleResultStringString handle,
}) => RustLib.instance.api.crateApiP2PJoinHandleResult(handle: handle);

Future<JoinHandleResultStringString> createServerWithFlags({
  required String username,
  required bool enableDhcp,
  required String specifiedIp,
  required String roomName,
  required String roomPassword,
  required List<String> severurl,
  required List<String> onurl,
  required List<String> cidrs,
  required List<Forward> forwards,
  required FlagsC flag,
}) => RustLib.instance.api.crateApiP2PCreateServerWithFlags(
  username: username,
  enableDhcp: enableDhcp,
  specifiedIp: specifiedIp,
  roomName: roomName,
  roomPassword: roomPassword,
  severurl: severurl,
  onurl: onurl,
  cidrs: cidrs,
  forwards: forwards,
  flag: flag,
);

Future<void> closeServer({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PCloseServer(instanceId: instanceId);

Future<List<PeerRoutePair>> getPeerRoutePairs({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PGetPeerRoutePairs(instanceId: instanceId);

Future<KVNetworkStatus> getNetworkStatus({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PGetNetworkStatus(instanceId: instanceId);

Future<void> initApp() => RustLib.instance.api.crateApiP2PInitApp();

/// Send a request-response RPC to `dst_peer_id` and await the typed reply.
Future<AppCallResultC> appCall({
  required String instanceId,
  required int dstPeerId,
  required String channel,
  required BigInt requestId,
  required List<int> payload,
  required int flags,
  required int timeoutMs,
}) => RustLib.instance.api.crateApiP2PAppCall(
  instanceId: instanceId,
  dstPeerId: dstPeerId,
  channel: channel,
  requestId: requestId,
  payload: payload,
  flags: flags,
  timeoutMs: timeoutMs,
);

/// Send a fire-and-forget notification to `dst_peer_id`. The RPC ack is still
/// awaited so the caller can detect routing failures within `timeout_ms`.
Future<void> appNotify({
  required String instanceId,
  required int dstPeerId,
  required String channel,
  required List<int> payload,
  required int timeoutMs,
}) => RustLib.instance.api.crateApiP2PAppNotify(
  instanceId: instanceId,
  dstPeerId: dstPeerId,
  channel: channel,
  payload: payload,
  timeoutMs: timeoutMs,
);

/// Round-trip ping. Returns the measured RTT in milliseconds.
Future<PlatformInt64> peerPing({
  required String instanceId,
  required int dstPeerId,
  required int timeoutMs,
}) => RustLib.instance.api.crateApiP2PPeerPing(
  instanceId: instanceId,
  dstPeerId: dstPeerId,
  timeoutMs: timeoutMs,
);

/// Stream inbound `Call` and `Notify` events from a running instance into
/// Dart. The future resolves once the EasyTier instance shuts down (the
/// underlying broadcast channel is closed); Dart can re-subscribe after a
/// subsequent `create_server` call.
Stream<AppInboundEventC> subscribeAppInbound({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PSubscribeAppInbound(instanceId: instanceId);

/// Reply to an inbound `Call` identified by `token`. Returns `true` if the
/// reply was delivered to the awaiting RPC task, `false` if the token was
/// already replied to / timed out / never existed.
///
/// `status == 0` is convention for "ok"; positive values are application
/// defined; negative values are reserved for transport-level codes (see
/// [`app_rpc_status`]).
Future<bool> appCallReply({
  required String instanceId,
  required BigInt token,
  required int status,
  required String errorMsg,
  required List<int> payload,
}) => RustLib.instance.api.crateApiP2PAppCallReply(
  instanceId: instanceId,
  token: token,
  status: status,
  errorMsg: errorMsg,
  payload: payload,
);

/// Number of `Call` events currently awaiting application replies for the
/// given instance. Useful for diagnostics / liveness checks from Dart.
Future<BigInt> pendingAppCallCount({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PPendingAppCallCount(instanceId: instanceId);

/// Local peer id for the given instance, exposed so Dart can label outgoing
/// traffic (the EasyTier route table uses the same `peer_id` space).
Future<int> myPeerId({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PMyPeerId(instanceId: instanceId);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EventBusSubscriber>>
abstract class EventBusSubscriber implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< JoinHandle < () >>>
abstract class JoinHandle implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JoinHandle < Result < String , String > >>>
abstract class JoinHandleResultStringString implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PeerRoutePair>>
abstract class PeerRoutePair implements RustOpaqueInterface {}

/// Result of [`app_call`] — directly maps `AppCallResponse` to a Dart record.
class AppCallResultC {
  final int status;
  final String errorMsg;
  final Uint8List payload;

  const AppCallResultC({
    required this.status,
    required this.errorMsg,
    required this.payload,
  });

  @override
  int get hashCode => status.hashCode ^ errorMsg.hashCode ^ payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppCallResultC &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          errorMsg == other.errorMsg &&
          payload == other.payload;
}

/// Inbound event delivered through [`subscribe_app_inbound`].
///
/// Modelled as a flat struct (rather than a Rust enum with payload variants)
/// so that the Dart binding stays a plain `dart class`, no `freezed` dep.
class AppInboundEventC {
  final AppInboundKindC kind;
  final int fromPeerId;
  final String channel;

  /// `request_id` echoed from the caller (0 for `Notify`).
  final BigInt requestId;

  /// Reply correlation token (0 for `Notify`). Pass to [`app_call_reply`].
  final BigInt token;
  final Uint8List payload;

  const AppInboundEventC({
    required this.kind,
    required this.fromPeerId,
    required this.channel,
    required this.requestId,
    required this.token,
    required this.payload,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      fromPeerId.hashCode ^
      channel.hashCode ^
      requestId.hashCode ^
      token.hashCode ^
      payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInboundEventC &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          fromPeerId == other.fromPeerId &&
          channel == other.channel &&
          requestId == other.requestId &&
          token == other.token &&
          payload == other.payload;
}

/// Discriminator for [`AppInboundEventC`].
enum AppInboundKindC {
  /// Request expecting a reply. Receiver MUST call [`app_call_reply`] with
  /// the carried `token`, otherwise the remote caller observes
  /// `app_rpc_status::REPLY_TIMEOUT` after the receiver-side timeout
  /// (default 30s, configured in EasyTier).
  call,

  /// Fire-and-forget notification (the sender already received an RPC-layer
  /// ack; this event is informational on the receiver side). For `Notify`
  /// events `request_id` and `token` are always 0.
  notify,
}

class FlagsC {
  final String defaultProtocol;
  final String devName;
  final bool enableEncryption;
  final bool enableIpv6;
  final int mtu;
  final bool latencyFirst;
  final bool enableExitNode;
  final bool noTun;
  final bool useSmoltcp;
  final String relayNetworkWhitelist;
  final bool disableP2P;
  final bool relayAllPeerRpc;
  final bool disableUdpHolePunching;
  final bool disableTcpHolePunching;
  final bool multiThread;
  final int dataCompressAlgo;
  final bool bindDevice;
  final bool enableKcpProxy;
  final bool disableKcpInput;
  final bool disableRelayKcp;
  final bool proxyForwardBySystem;
  final bool acceptDns;
  final bool privateMode;
  final bool enableQuicProxy;
  final bool disableQuicInput;
  final bool disableSymHolePunching;
  final String tcpWhitelist;
  final String udpWhitelist;

  const FlagsC({
    required this.defaultProtocol,
    required this.devName,
    required this.enableEncryption,
    required this.enableIpv6,
    required this.mtu,
    required this.latencyFirst,
    required this.enableExitNode,
    required this.noTun,
    required this.useSmoltcp,
    required this.relayNetworkWhitelist,
    required this.disableP2P,
    required this.relayAllPeerRpc,
    required this.disableUdpHolePunching,
    required this.disableTcpHolePunching,
    required this.multiThread,
    required this.dataCompressAlgo,
    required this.bindDevice,
    required this.enableKcpProxy,
    required this.disableKcpInput,
    required this.disableRelayKcp,
    required this.proxyForwardBySystem,
    required this.acceptDns,
    required this.privateMode,
    required this.enableQuicProxy,
    required this.disableQuicInput,
    required this.disableSymHolePunching,
    required this.tcpWhitelist,
    required this.udpWhitelist,
  });

  @override
  int get hashCode =>
      defaultProtocol.hashCode ^
      devName.hashCode ^
      enableEncryption.hashCode ^
      enableIpv6.hashCode ^
      mtu.hashCode ^
      latencyFirst.hashCode ^
      enableExitNode.hashCode ^
      noTun.hashCode ^
      useSmoltcp.hashCode ^
      relayNetworkWhitelist.hashCode ^
      disableP2P.hashCode ^
      relayAllPeerRpc.hashCode ^
      disableUdpHolePunching.hashCode ^
      disableTcpHolePunching.hashCode ^
      multiThread.hashCode ^
      dataCompressAlgo.hashCode ^
      bindDevice.hashCode ^
      enableKcpProxy.hashCode ^
      disableKcpInput.hashCode ^
      disableRelayKcp.hashCode ^
      proxyForwardBySystem.hashCode ^
      acceptDns.hashCode ^
      privateMode.hashCode ^
      enableQuicProxy.hashCode ^
      disableQuicInput.hashCode ^
      disableSymHolePunching.hashCode ^
      tcpWhitelist.hashCode ^
      udpWhitelist.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlagsC &&
          runtimeType == other.runtimeType &&
          defaultProtocol == other.defaultProtocol &&
          devName == other.devName &&
          enableEncryption == other.enableEncryption &&
          enableIpv6 == other.enableIpv6 &&
          mtu == other.mtu &&
          latencyFirst == other.latencyFirst &&
          enableExitNode == other.enableExitNode &&
          noTun == other.noTun &&
          useSmoltcp == other.useSmoltcp &&
          relayNetworkWhitelist == other.relayNetworkWhitelist &&
          disableP2P == other.disableP2P &&
          relayAllPeerRpc == other.relayAllPeerRpc &&
          disableUdpHolePunching == other.disableUdpHolePunching &&
          disableTcpHolePunching == other.disableTcpHolePunching &&
          multiThread == other.multiThread &&
          dataCompressAlgo == other.dataCompressAlgo &&
          bindDevice == other.bindDevice &&
          enableKcpProxy == other.enableKcpProxy &&
          disableKcpInput == other.disableKcpInput &&
          disableRelayKcp == other.disableRelayKcp &&
          proxyForwardBySystem == other.proxyForwardBySystem &&
          acceptDns == other.acceptDns &&
          privateMode == other.privateMode &&
          enableQuicProxy == other.enableQuicProxy &&
          disableQuicInput == other.disableQuicInput &&
          disableSymHolePunching == other.disableSymHolePunching &&
          tcpWhitelist == other.tcpWhitelist &&
          udpWhitelist == other.udpWhitelist;
}

class Forward {
  final String bindAddr;
  final String dstAddr;
  final String proto;

  const Forward({
    required this.bindAddr,
    required this.dstAddr,
    required this.proto,
  });

  @override
  int get hashCode => bindAddr.hashCode ^ dstAddr.hashCode ^ proto.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Forward &&
          runtimeType == other.runtimeType &&
          bindAddr == other.bindAddr &&
          dstAddr == other.dstAddr &&
          proto == other.proto;
}

class KVNetworkStatus {
  final BigInt totalNodes;
  final List<KVNodeInfo> nodes;

  const KVNetworkStatus({required this.totalNodes, required this.nodes});

  @override
  int get hashCode => totalNodes.hashCode ^ nodes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KVNetworkStatus &&
          runtimeType == other.runtimeType &&
          totalNodes == other.totalNodes &&
          nodes == other.nodes;
}

class KVNodeConnectionStats {
  final String connType;
  final BigInt rxBytes;
  final BigInt txBytes;
  final BigInt rxPackets;
  final BigInt txPackets;

  const KVNodeConnectionStats({
    required this.connType,
    required this.rxBytes,
    required this.txBytes,
    required this.rxPackets,
    required this.txPackets,
  });

  @override
  int get hashCode =>
      connType.hashCode ^
      rxBytes.hashCode ^
      txBytes.hashCode ^
      rxPackets.hashCode ^
      txPackets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KVNodeConnectionStats &&
          runtimeType == other.runtimeType &&
          connType == other.connType &&
          rxBytes == other.rxBytes &&
          txBytes == other.txBytes &&
          rxPackets == other.rxPackets &&
          txPackets == other.txPackets;
}

class KVNodeInfo {
  final int peerId;
  final String hostname;
  final String ipv4;
  final String ipv6;
  final double latencyMs;
  final String nat;
  final List<NodeHopStats> hops;
  final double lossRate;
  final List<KVNodeConnectionStats> connections;
  final String tunnelProto;
  final String connType;
  final BigInt rxBytes;
  final BigInt txBytes;
  final String version;
  final int cost;

  const KVNodeInfo({
    required this.peerId,
    required this.hostname,
    required this.ipv4,
    required this.ipv6,
    required this.latencyMs,
    required this.nat,
    required this.hops,
    required this.lossRate,
    required this.connections,
    required this.tunnelProto,
    required this.connType,
    required this.rxBytes,
    required this.txBytes,
    required this.version,
    required this.cost,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      hostname.hashCode ^
      ipv4.hashCode ^
      ipv6.hashCode ^
      latencyMs.hashCode ^
      nat.hashCode ^
      hops.hashCode ^
      lossRate.hashCode ^
      connections.hashCode ^
      tunnelProto.hashCode ^
      connType.hashCode ^
      rxBytes.hashCode ^
      txBytes.hashCode ^
      version.hashCode ^
      cost.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KVNodeInfo &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          hostname == other.hostname &&
          ipv4 == other.ipv4 &&
          ipv6 == other.ipv6 &&
          latencyMs == other.latencyMs &&
          nat == other.nat &&
          hops == other.hops &&
          lossRate == other.lossRate &&
          connections == other.connections &&
          tunnelProto == other.tunnelProto &&
          connType == other.connType &&
          rxBytes == other.rxBytes &&
          txBytes == other.txBytes &&
          version == other.version &&
          cost == other.cost;
}

class NodeHopStats {
  final int peerId;
  final String targetIp;
  final double latencyMs;
  final double packetLoss;
  final String nodeName;

  const NodeHopStats({
    required this.peerId,
    required this.targetIp,
    required this.latencyMs,
    required this.packetLoss,
    required this.nodeName,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      targetIp.hashCode ^
      latencyMs.hashCode ^
      packetLoss.hashCode ^
      nodeName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodeHopStats &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          targetIp == other.targetIp &&
          latencyMs == other.latencyMs &&
          packetLoss == other.packetLoss &&
          nodeName == other.nodeName;
}
